version: '3.2'

networks:
  app-network:
volumes:
  db-data:

services:
  rbh-go-app:
    build:
      context: .
      dockerfile: dockerfile-app.yml
    depends_on:
      - rbh-db
    networks:
      - app-network
    ports:
      - "8080:8080"
  rbh-db:
    build:
      context: .
      dockerfile: dockerfile-db.yml
    networks:
      - app-network
    volumes:
        - db-data:/var/lib/mysql
